### ISSUE TITLE
投稿录播的标题能否自动适应为当前直播间名称

### ISSUE THREAD

**Issue by Sinsax** [AsaChiri/DDRecorder#15]
投稿标题如果是日期加当天直播间名称,感觉会便于后期翻查

**Comment by ZhaoWeicheng98** [comment]
感谢反馈，这个功能可以考虑增加，不过大概率只支持直播开始的直播间名称。
（很抱歉之前忙于其他工作，这边没有太多时间回复和维护）

**Comment by ZhaoWeicheng98** [comment]
1.2.0增加了相应的占位符
