### ISSUE TITLE
长时间运行造成大量空目录

### ISSUE THREAD

**Issue by qfan** [AsaChiri/DDRecorder#17]
**Describe the bug**
长时间运行后，会生成大量空目录

**To Reproduce**
1. 监控两个直播时间不定的直播间
2. 几天后发现数据输出目录中的绝大多数子目录都是空的

**Expected behavior**
不应该生成大量空目录。

**Screenshots**
![image](https://user-images.githubusercontent.com/1900202/113887040-fefea080-9775-11eb-8365-9955abfd5f00.png)

**Desktop (please complete the following information):**
 - OS: VMWare运行的Ubuntu 20.04 LTS，文件输出位置为远程绑定（SMB cifs /etc/fstab自动挂载）的win10共享目录。

**Comment by ZhaoWeicheng98** [comment]
您好，感谢您的反馈，空目录是由于B站开播状态与实际推流的存在与否不同步导致的（即B站开播了，但是还没有开始推流；或者掐掉了推流，但是B站没有点击关闭直播），在这个过程中，如果程序在多次重试后没有能够连接到推流，就会认为直播结束了，因此会产生空文件夹。
后续将会通过适当地调整重试次数或引入其他手段减少空文件夹产生同时不影响中途断线后的重连速度。

**Comment by ZhaoWeicheng98** [comment]
1.2.0尝试修复了这个问题，您看看？

**Comment by qfan** [comment]
> 1.2.0尝试修复了这个问题，您看看？

试着挂了半晚上，目前看来已经比以前干净多了。

仅剩的小问题就是outputs和splits下对应每次直播生成各一个目录，即使没有自动切片出来也会保留这些空目录。
![image](https://user-images.githubusercontent.com/1900202/153287888-d26c1377-909e-47b3-94ae-073826fd5306.png)
