### ISSUE TITLE
上传成功后不会自动删除录播文件

### ISSUE THREAD

**Issue by gabriel254** [AsaChiri/DDRecorder#18]
使用的是latest(edba21222ad1224916cb22a0c3c4f0dcf7572099)编译的Docker版跑在Ubuntu18.04上。
`config.json`里已经设置`"keep_raw_record" : false` 和 `"keep_record_after_upload": false`
今天发现昨天的录播上传成功且过审之后，数据文件夹内`records`是没有没有视频文件的（应该是`"keep_raw_record" : false`参数起了作用），但`merged`文件夹内保留了完整的录像mp4文件以及`splits`文件夹内保留了所有split的mp4文件，`"keep_record_after_upload": false`参数并没有起到作用。

完整的`config.json`如下：
```json
{
  "root": {
    "check_interval": 120,
    "print_interval": 10,
    "data_path": "/downloads",
    "logger": { "log_path": "/app/log", "log_level": "DEBUG" },
    "request_header": {},
    "uploader": {
      "upload_by_edit": true,
      "thread_pool_workers": 4,
      "max_retry": 10
    },
    "enable_baiduyun": false
  },
  "spec": [
    {
      "room_id": "22637920",
      "recorder": { "keep_raw_record": false },
      "parser": {
        "interval": 30,
        "up_ratio": 2.5,
        "down_ratio": 0.75,
        "topK": 5
      },
      "clipper": {
        "enable_clipper": false,
        "min_length": 60,
        "start_offset": -20,
        "end_offset": 10
      },
      "uploader": {
        "account": {
          "username": "xxxxxx",
          "password": "xxxxxx"
        },
        "copyright": 2,
        "record": {
          "upload_record": true,
          "keep_record_after_upload": false,
          "split_interval": 3600,
          "title": "{date} 直播录播",
          "tid": 65,
          "tags": ["直播录播"],
          "desc": "本视频由全自动切片型智能DD机剪辑上传~"
        },
        "clips": {
          "upload_clips": false,
          "keep_clips_after_upload": false,
          "title": "{date} 直播精彩剪辑【自动切片】",
          "tid": 65,
          "tags": ["直播录播"],
          "desc": "本视频由全自动切片型智能DD机剪辑上传~"
        }
      },
      "backup": false
    }
  ]
}

```

**Comment by ZhaoWeicheng98** [comment]
感谢反馈。"keep_record_after_upload": false不起作用的问题会尽快修正。
“merged文件夹内保留了完整的录像mp4文件”这个问题目前原因是百度网盘侧返回的MD5与本地文件不一致，这个问题目前仍然在调查具体原因（因为这部分是使用的bypy第三方库，而且也不能确定百度网盘那边的返回的MD5到底是怎么个情况这样）（手动捂脸）

**Comment by gabriel254** [comment]
我目前的做法是把`config.json`里加个参数，具体请看这里https://github.com/gabriel254/DDRecorder/commit/0e3e788d42b9f6d789206e10b13ce087456c47e8

**Comment by gabriel254** [comment]
另外再提供一个反馈信息，`"keep_record_after_upload": false`这块代码是在这里体现https://github.com/AsaChiri/DDRecorder/blob/26cfce1e9e37b22cb31e681d018b76710f56490f/BiliVideoChecker.py#L48-L59
但不清楚为啥这块代码好像一直没有执行，因为我在`Main_{date}.log`里并没有找到关于稿件上传的消息。
还有一点就是使用`check_url `返回来的json信息检查后并删除文件可能会有一些问题，使用是`upload_by_edit`上传时，第一分P的很早就会开始审核，导致后面的分P可能刚上传完，前面一些分P的已经过审了，然后就已经拿到`bvid `了。然后执行删除操作之后，所有splits都会被删掉。但是我检查了一下，这这个`check_url `返回来的json信息只会包含了已过审的分P，还在审核中的分P并不会在这里面显示出来。如果后面的一些分P不过审，想要再修改一下重新投稿就没办法了，因为该split文件已经被删掉了。

**Comment by gabriel254** [comment]
我目前想到的解决办法是，偷懒一点就在README里推荐不要使用`upload_by_edit `上传，使用`upload_by_edit `时最好打开`keep_record_after_upload `选项。
另一个做法就是，根据`check_url`返回来的json信息里，`video_info['data']['pages']`是一个列表，包含了每一分P的详情，可以根据分P的标题来删除对应的split文件。比如第x分P标题`video_info['data']['pages'][x]['part']`就对应第x个split文件

**Comment by ZhaoWeicheng98** [comment]
> 另外再提供一个反馈信息，`"keep_record_after_upload": false`这块代码是在这里体现
> 
> https://github.com/AsaChiri/DDRecorder/blob/26cfce1e9e37b22cb31e681d018b76710f56490f/BiliVideoChecker.py#L48-L59
> 
> 
> 但不清楚为啥这块代码好像一直没有执行，因为我在`Main_{date}.log`里并没有找到关于稿件上传的消息。
> 还有一点就是使用`check_url `返回来的json信息检查后并删除文件可能会有一些问题，使用是`upload_by_edit`上传时，第一分P的很早就会开始审核，导致后面的分P可能刚上传完，前面一些分P的已经过审了，然后就已经拿到`bvid `了。然后执行删除操作之后，所有splits都会被删掉。但是我检查了一下，这这个`check_url `返回来的json信息只会包含了已过审的分P，还在审核中的分P并不会在这里面显示出来。如果后面的一些分P不过审，想要再修改一下重新投稿就没办法了，因为该split文件已经被删掉了。

感谢反馈。这个部分的日志应该是记录在VideoCehcker_*.log这样的日志文件里的，您看一下是否有对应的日志文件，如果可以的话烦请发送以分析。
关于分P的问题，这边确实是疏忽了（因为通过编辑投稿的功能加在之后，因此有欠考虑）。烦请先暂时不使用编辑上传的功能，我会尽快将两者进行适配。

**Comment by ZhaoWeicheng98** [comment]
编辑投稿与删除冲突通过增加删除时判断编辑投稿是否启用实现；另外关于百度云的问题，经查是百度云修改hash计算方法导致的，bypy那边已经找到问题并更新了，更新bypy版本即可。
