### ISSUE TITLE
建议支持单个命令监听多个直播间

### ISSUE THREAD

**Issue by sola614** [AsaChiri/DDRecorder#3]
在服务器部署，一个就要占130+m内存，多了就遭不住了
最好再来个油管录播上传功能

**Comment by ZhaoWeicheng98** [comment]
监听多个直播间这个功能正在做，目前考虑的方法是外面再包一层然后多进程出去。

油管直播这个等之后折腾一下，顺便可能的话把twitch和douyu也弄进去，不过这个需要一些时间。

**Comment by ZhaoWeicheng98** [comment]
晚上好，目前Feature-all-in-one分支中的代码已经改为单个命令监听多个直播间，同时提供了开箱即用的exe文件，并优化了控制台输出，欢迎试用并提出您的意见和建议。

**Comment by sola614** [comment]
刚在服务器上试了下，报了这个问题
![pic1](https://user-images.githubusercontent.com/36149249/104977827-722c2c80-5a3b-11eb-814e-dd80555ca904.png)
另外在window10系统下使用exe文件的话，如果有报错，窗口会闪退，不报错的情况下暂时没问题
