### ISSUE TITLE
大佬，这个上传是上传到哪里的？

### ISSUE THREAD

**Issue by zhezhe168** [AsaChiri/DDRecorder#31]
想要个批量上传本地视频的功能，不知道能不能实现？

**Comment by ZhaoWeicheng98** [comment]
有上传到B站投稿的功能，也有上传到百度云的功能，前者利用BilibiliUploader（https://github.com/FortuneDayssss/BilibiliUploader），后者利用bypy（https://github.com/houtianze/bypy）
