### ISSUE TITLE
手动切片

### ISSUE THREAD

**Issue by CyanTailwinds** [AsaChiri/DDRecorder#32]
请问有没有可能增加手动切片功能, 比如自己在看的时候,看到想要切的地方, 一键保存历史x分钟, 然后自己再对获得的视频文件做别的编辑等  类似nvidia驱动自带的阴影时间

**Comment by ZhaoWeicheng98** [comment]
感谢建议！

**Comment by ZhaoWeicheng98** [comment]
1.2.0增加了手动切片功能。
