### ISSUE TITLE
录制文件占用空间过大

### ISSUE THREAD

**Issue by yulinlin404** [AsaChiri/DDRecorder#36]
大佬，为什么录制文件有flv和ts格式的啊
一场直播下来就是两份一样的文件，只是格式不同
而且records文件夹里还有很多0kb的flv文件
然后为什么merged还有一份mp4文件啊
开了切割还会在splits里每小时一个文件
几乎就是一场直播，四份一样的。。。

**Comment by ZhaoWeicheng98** [comment]
首先说解决问题的办法，将设置中的keep_raw_record，keep_record_after_upload，keep_clips_after_upload设置为false程序会自动清理无用文件。

其中的情况是，B站直播源为flv格式，你看到的flv格式文件就是录制的直播源文件。flv格式可能存在时间轴问题，为了将直播中可能裂开成几段的flv文件连起来，需要统一修复时间轴，因此转换为了ts格式，然后合并成mp4. flv文件和ts文件在keep_raw_record为false时会自动清理。合并后的mp4在merged文件夹下，是后续处理的基础，也是用于备份到网盘的文件，此文件如果开启了备份到百度网盘则会在备份完成后清理。splits和outputs下是生成的用于上传的视频文件，录播默认会每小时截断来防止上传者没有上传超大文件的权限，在keep_record_after_upload，keep_clips_after_upload为false时，这些文件会在视频上传过审后清理。

最后很多0kb的flv文件这是软件目前的一个问题，因为B站请求不能过于频繁，因此软件对于是否开播的状态和B站的状态有一定不同步，此外B站上是否开播的状态与主播有没有把推流掐了但是没有点下播也是不同步的（B站允许至多5分钟的空推流即开播但没有推流数据），在这段时间内，软件会反复尝试链接以防出现网络断连的情况，因此产生了很多0kb的录像文件。不过这些文件所长空间几乎可以忽略不计，后续可能会考虑定时去清理这些小文件。
