### ISSUE TITLE
b站更新投稿工具后，账号无法登录

### ISSUE THREAD

**Issue by myishh** [AsaChiri/DDRecorder#37]
尝试了多个账号，更换IP也不行，全部提示如下：

{'code': 86066, 'message': '该账号冻结中', 'ttl': 1, 'data': None}

**Comment by ZhaoWeicheng98** [comment]
BilibiliUploader更新后已经修复，请执行pip install -r ./requirements.txt -U 或者在release页面下载最新构建。
