### ISSUE TITLE
希望加入弹幕过滤功能

### ISSUE THREAD

**Issue by yulinlin404** [AsaChiri/DDRecorder#38]
最近不是有那个粉丝团灯牌活动嘛，然后有个感谢机器人一直刷屏，自动切片切出来的没法看。
希望可以屏蔽用户或者屏蔽关键词。
（最近dd机自动切片没法看，自己翻弹幕文件xml也是抓不到高能点，全被感谢礼物机器人淹没了）

以及，我倍率已经拉很高了，但还是感觉没抓到点上，是不是主播太拉了，切片机也切不出
![屏幕截图 2021-12-10 023104](https://user-images.githubusercontent.com/49760859/145455204-4c193641-19bc-4b28-8567-dcd572f58ee9.png)

额，还有，我明明release页面下的最新的，运行起来还是提示有更新？

**Comment by ZhaoWeicheng98** [comment]
1.感谢建议，可以考虑添加；
2.忘记更新最新版本版本号了orz（
