### ISSUE TITLE
视频处理完毕后，程序回报“系统找不到指定的文件”，无法上传录播

### ISSUE THREAD

**Issue by PYXXXX** [AsaChiri/DDRecorder#42]
录制结束，视频处理完毕后，程序提示“系统找不到指定的文件”，随后提示开始上传，但系统此时并没有上传活动（）
![E82D0292-6489-45C4-B347-331A00A7C448](https://user-images.githubusercontent.com/85445850/150087243-5dc48af9-b182-465e-8cbe-6f85341893da.jpeg)
![B1D8683B-5D42-4FDD-8C81-F3BA5512CFB1](https://user-images.githubusercontent.com/85445850/150087254-7e6c9813-d582-41bc-bef1-a04af55e40f8.jpeg)

**Comment by PYXXXX** [comment]
（已经拉取了requirements.txt）

**Comment by PYXXXX** [comment]
（已经拉取了requirements.txt，安装了python及ffmpeg并配置环境变量（（

**Comment by ZhaoWeicheng98** [comment]
看起来是视频处理过程中出现了问题，导致没能够产生视频用于上传，你可以检查一下logs文件夹下的日志文件，看一下是否有报错

**Comment by ZhaoWeicheng98** [comment]
我确认这是由于我所使用的上传库的问题引发的，我今天会更改上传库使用[ForgQi/biliup](https://github.com/ForgQi/biliup) 来修复这一问题，同时增加cookie登录的方式

**Comment by ZhaoWeicheng98** [comment]
1.2.0应该修复了这个问题，请尝试通过access_token进行登录。
