### ISSUE TITLE
编译出的DDRecorder.exe无法正常运行

### ISSUE THREAD

**Issue by BuArcher** [AsaChiri/DDRecorder#48]
打开DDRecorder.exe后
```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "MainRunner.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "DanmuRecorder.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "brotli\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "brotli\brotli.py", line 5, in <module>
ModuleNotFoundError: No module named '_cffi_backend'
[24396] Failed to execute script 'main' due to unhandled exception!
```
大概是封包时cffi模组出错

**Comment by ZhaoWeicheng98** [comment]
我重新打包一下，感谢反馈！

**Comment by ZhaoWeicheng98** [comment]
重新打包了，应当OK了

> 打开DDRecorder.exe后
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 12, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "MainRunner.py", line 12, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "DanmuRecorder.py", line 13, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "brotli\__init__.py", line 3, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "brotli\brotli.py", line 5, in <module>
> ModuleNotFoundError: No module named '_cffi_backend'
> [24396] Failed to execute script 'main' due to unhandled exception!
> ```
> 
> 大概是封包时cffi模组出错

**Comment by archerlingge** [comment]
还有一个问题，关于DDRecorderConfigManager.exe在主播特定设置录入access_token和refresh_token后再次打开被编辑过的Config。发现两项被清空，这个是bug还是特性？

**Comment by ZhaoWeicheng98** [comment]
> 还有一个问题，关于DDRecorderConfigManager.exe在主播特定设置录入access_token和refresh_token后再次打开被编辑过的Config。发现两项被清空，这个是bug还是特性？

这个应该是bug，我尽快修（因为ConfigManager主要还是方便不会直接编辑json文件的用户写的，写的比较粗糙，bug比较多，如果会直接编辑json文件的话建议直接改json文件。）

**Comment by archerlingge** [comment]
> > 还有一个问题，关于DDRecorderConfigManager.exe在主播特定设置录入access_token和refresh_token后再次打开被编辑过的Config。发现两项被清空，这个是bug还是特性？
> 
> 这个应该是bug，我尽快修（因为ConfigManager主要还是方便不会直接编辑json文件的用户写的，写的比较粗糙，bug比较多，如果会直接编辑json文件的话建议直接改json文件。）

好的了解

**Comment by ZhaoWeicheng98** [comment]
> > > 还有一个问题，关于DDRecorderConfigManager.exe在主播特定设置录入access_token和refresh_token后再次打开被编辑过的Config。发现两项被清空，这个是bug还是特性？
> > 
> > 
> > 这个应该是bug，我尽快修（因为ConfigManager主要还是方便不会直接编辑json文件的用户写的，写的比较粗糙，bug比较多，如果会直接编辑json文件的话建议直接改json文件。）
> 
> 好的了解

此问题已在1.2.3随附的DDRecorderConfigManager中修复（不用填了，直接提供按钮进行鉴权）
