### ISSUE TITLE
电磁力低于LV3自动投稿分P功能失效

### ISSUE THREAD

**Issue by garfieldwlx** [AsaChiri/DDRecorder#50]
环境：win10
软件版本：1.2.1
账号等级lv1
录播和切片的分P功能无效，自动投稿变成单P稿件

PS：目前网页端无法多P投稿，ForgQi/Caution这个项目目前可以通过客户端口提交多P稿件

**Comment by ForgQi** [comment]
调用上传的库也可以试一下biliup，定时发布也是支持的
https://forgqi.github.io/biliup/API-reference.html
```python
from biliup.plugins.bili_webup import BiliBili, Data

video = Data()
video.title = '视频标题'
video.desc = '视频简介'
video.source = '添加转载地址说明'
# 设置视频分区,默认为160 生活分区
video.tid = 171
video.set_tag(['星际争霸2', '电子竞技'])
with BiliBili(video) as bili:
    bili.login_by_password("username", "password")
    for file in file_list:
        video_part = bili.upload_file(file)  # 上传视频
        video.append(video_part)  # 添加已经上传的视频
    video.cover = bili.cover_up('/cover_path').replace('http:', '')
    ret = bili.submit()  # 提交视频
```

**Comment by satouriko** [comment]
我也是的，split 时间设多少就只上传了开始那么长时间的那一段

**Comment by satouriko** [comment]
另外我在想，能不能按照文件大小而不是时长来分，因为我感觉b站的上传限制是文件大小，不同类型的视频码率差的还挺大的（比如游戏就比虚拟主播大很多）

**Comment by ZhaoWeicheng98** [comment]
> 调用上传的库也可以试一下biliup，定时发布也是支持的 https://forgqi.github.io/biliup/API-reference.html
> 
> ```python
> from biliup.plugins.bili_webup import BiliBili, Data
> 
> video = Data()
> video.title = '视频标题'
> video.desc = '视频简介'
> video.source = '添加转载地址说明'
> # 设置视频分区,默认为160 生活分区
> video.tid = 171
> video.set_tag(['星际争霸2', '电子竞技'])
> with BiliBili(video) as bili:
>     bili.login_by_password("username", "password")
>     for file in file_list:
>         video_part = bili.upload_file(file)  # 上传视频
>         video.append(video_part)  # 添加已经上传的视频
>     video.cover = bili.cover_up('/cover_path').replace('http:', '')
>     ret = bili.submit()  # 提交视频
> ```

非常感谢，想请问一下biliup是否有分P标题和稿件编辑功能，我之前看了API文档和源码似乎没有。如果确实没有我找个时间研究一下增加相关功能进行贡献，之后使用biliup替换项目中的上传库。

**Comment by ZhaoWeicheng98** [comment]
> 环境：win10 软件版本：1.2.1 账号等级lv1 录播和切片的分P功能无效，自动投稿变成单P稿件
> 
> PS：目前网页端无法多P投稿，ForgQi/Caution这个项目目前可以通过客户端口提交多P稿件

另外也有可能和upload_by_edit有关，你关掉这个功能试一下？

**Comment by ForgQi** [comment]
> > 调用上传的库也可以试一下biliup，定时发布也是支持的 https://forgqi.github.io/biliup/API-reference.html
> > ```python
> > from biliup.plugins.bili_webup import BiliBili, Data
> > 
> > video = Data()
> > video.title = '视频标题'
> > video.desc = '视频简介'
> > video.source = '添加转载地址说明'
> > # 设置视频分区,默认为160 生活分区
> > video.tid = 171
> > video.set_tag(['星际争霸2', '电子竞技'])
> > with BiliBili(video) as bili:
> >     bili.login_by_password("username", "password")
> >     for file in file_list:
> >         video_part = bili.upload_file(file)  # 上传视频
> >         video.append(video_part)  # 添加已经上传的视频
> >     video.cover = bili.cover_up('/cover_path').replace('http:', '')
> >     ret = bili.submit()  # 提交视频
> > ```
> 
> 非常感谢，想请问一下biliup是否有分P标题和稿件编辑功能，我之前看了API文档和源码似乎没有。如果确实没有我找个时间研究一下增加相关功能进行贡献，之后使用biliup替换项目中的上传库。

分P标题有，修改返回的video_part即可。稿件编辑确实是没有，先感谢大佬PR了

**Comment by ZhaoWeicheng98** [comment]
v1.2.3已更新有关上传的部分
