### ISSUE TITLE
在CentOS 7.9下安装时报错 ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.

### ISSUE THREAD

**Issue by Funny-ppt** [AsaChiri/DDRecorder#54]
via 阿里云ECS服务器
OS = CentOS 7.9
python = 3.10.2

下面是报错细节
`[root@iZuf65sjhgk33mv8gbk7e2Z DDRecorder]# python -m pip install -r requirements.txt
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting git+git://github.com/FortuneDayssss/BilibiliUploader.git (from -r requirements.txt (line 58))
  Cloning git://github.com/FortuneDayssss/BilibiliUploader.git to /tmp/pip-req-build-wenebb5a
  Running command git clone --quiet git://github.com/FortuneDayssss/BilibiliUploader.git /tmp/pip-req-build-wenebb5a
  Resolved git://github.com/FortuneDayssss/BilibiliUploader.git to commit 23266861c155c75eae5a29a424a15d87da81c132
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

请问应该怎么解决？

**Comment by ZhaoWeicheng98** [comment]
考虑安装一下setuptools

**Comment by Funny-ppt** [comment]
> 考虑安装一下setuptools

我之前已经用py （版本3.10.2）的pip更新过setuptools了，是最新版

**Comment by ZhaoWeicheng98** [comment]
现在requirements更新了（而且不使用bilibiliuploader了，您看看现在可以了吗
