### ISSUE TITLE
录播结束后，切片成功上传，录播未能上传

### ISSUE THREAD

**Issue by 502y** [AsaChiri/DDRecorder#57]
**Describe the bug**
单直播间录播结束后，切片和按时间分割的录播文件正常生成。切片自动上传完毕，录播未能上传。填写了账号、密码、access_token、refresh_token。

**Comment by infinity-M** [comment]
可以检查下config中是否填写正确，顺便看下log文件中怎么说

**Comment by 502y** [comment]
> 

好的，我再看看
