### ISSUE TITLE
请求加入上传路线手动选择功能

### ISSUE THREAD

**Issue by infinity-M** [AsaChiri/DDRecorder#71]
biliup内置了 ws qn bda2 kodo gcs bos cos等多个上传线路，auto模式下检测延迟后自动选择

但海外vps及某些特殊情况下，kodo等线路延迟会较大，但却可以跑满带宽，故经常不会被auto模式选中，而选中某些低速线路。

故请求加入可配置的lines参数

biliup的配置文件：
b站上传线路选择，默认为自动模式，目前可手动切换为bda2, kodo, ws, qn, cos, cos-internal(支持腾讯云内网免流+提速)
lines: AUTO
嵌入库例子：
for file in file_list:
        video_part = bili.upload_file(file, lines=lines, tasks=tasks)

（感谢大佬，我太菜了不然我就pr了QAQ）

**Comment by ZhaoWeicheng98** [comment]
感谢反馈，已在最新版中添加
