### ISSUE TITLE
【bug】最新版exe文件运行报错

### ISSUE THREAD

**Issue by DYS763** [AsaChiri/DDRecorder#74]
Thu, 21 Jul 2022 22:18:54 18996 MainThread retry.py[line:351] DEBUG Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
Thu, 21 Jul 2022 22:18:54 19340 Thread-1 ProjectHolder.py[line:58] INFO Using cache directory: C:\Users\asus\AppData\Local\lastversion\lastversion\Cache.
Thu, 21 Jul 2022 22:18:54 18996 MainThread connectionpool.py[line:1001] DEBUG Starting new HTTPS connection (1): api.live.bilibili.com:443
Thu, 21 Jul 2022 22:18:54 19340 Thread-1 ProjectHolder.py[line:65] INFO Created instance of GitHubRepoSession
Thu, 21 Jul 2022 22:18:54 19340 Thread-1 controller.py[line:132] DEBUG Looking up "https://github.com/AsaChiri/DDRecorder/releases.atom" in the cache
Thu, 21 Jul 2022 22:18:54 19340 Thread-1 controller.py[line:147] DEBUG No cache entry available
Thu, 21 Jul 2022 22:18:54 19340 Thread-1 connectionpool.py[line:1001] DEBUG Starting new HTTPS connection (1): github.com:443
Thu, 21 Jul 2022 22:18:54 18996 MainThread retry.py[line:594] DEBUG Incremented Retry for (url='/room/v1/Room/get_info?room_id=92613'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
Thu, 21 Jul 2022 22:18:54 18996 MainThread connectionpool.py[line:810] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /room/v1/Room/get_info?room_id=92613
Thu, 21 Jul 2022 22:18:54 18996 MainThread connectionpool.py[line:1001] DEBUG Starting new HTTPS connection (2): api.live.bilibili.com:443
Thu, 21 Jul 2022 22:18:55 18996 MainThread retry.py[line:594] DEBUG Incremented Retry for (url='/room/v1/Room/get_info?room_id=92613'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
Thu, 21 Jul 2022 22:18:55 18996 MainThread connectionpool.py[line:810] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /room/v1/Room/get_info?room_id=92613
Thu, 21 Jul 2022 22:18:55 18996 MainThread connectionpool.py[line:1001] DEBUG Starting new HTTPS connection (3): api.live.bilibili.com:443
Thu, 21 Jul 2022 22:18:55 18996 MainThread retry.py[line:594] DEBUG Incremented Retry for (url='/room/v1/Room/get_info?room_id=92613'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
Thu, 21 Jul 2022 22:18:55 18996 MainThread connectionpool.py[line:810] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /room/v1/Room/get_info?room_id=92613
Thu, 21 Jul 2022 22:18:55 18996 MainThread connectionpool.py[line:1001] DEBUG Starting new HTTPS connection (4): api.live.bilibili.com:443
Thu, 21 Jul 2022 22:18:55 18996 MainThread BaseLive.py[line:48] ERROR [Site:BiliBili Room:92613] Request ErrorHTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /room/v1/Room/get_info?room_id=92613 (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 994, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 499, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 813, in urlopen
  File "urllib3\connectionpool.py", line 813, in urlopen
  File "urllib3\connectionpool.py", line 813, in urlopen
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /room/v1/Room/get_info?room_id=92613 (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BaseLive.py", line 41, in common_request
  File "requests\sessions.py", line 542, in get
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /room/v1/Room/get_info?room_id=92613 (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

Thu, 21 Jul 2022 22:18:55 18996 MainThread __init__.py[line:14] ERROR Uncaught exception:
Traceback (most recent call last):
  File "main.py", line 77, in <module>
  File "MainRunner.py", line 126, in __init__
  File "MainRunner.py", line 27, in __init__
  File "BiliLive.py", line 16, in __init__
  File "BiliLive.py", line 23, in get_room_info
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by ZhaoWeicheng98** [comment]
看起来是无法正常链接到bilibili api地址导致的，您可以先检查一下网络~
