### ISSUE TITLE
下载1.3.0后提示无法获取DDRecorder的版本信息，当前版本号: {}，请到https://github.com/AsaChiri/DDRecorder/releases 检查最新版本'.format(CURRENT_VERSION))

### ISSUE THREAD

**Issue by lsnan0209** [AsaChiri/DDRecorder#76]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZhaoWeicheng98** [comment]
可能是与github链接不畅导致的，此消息应当不影响正常使用。
