### ISSUE TITLE
录制403报错（出现大量flv文件）的解决方法

### ISSUE THREAD

**Issue by ZTMMZ** [AsaChiri/DDRecorder#87]
**解决方法**
BiliLiveRecorder.py, line 28
把请求头Referer字段的值改成固定的`'https://live.bilibili.com/'`即可

**适用于控制台无明显报错，但是data/records/对应目录下出现大量552bytes的、内容为html 403报错的flv文件**

2022年12月大概第二周左右开始就出现这个问题了，应该是B站改了直播流的Referer校验。总之如果能排除风控问题可以试一下这个解决方案。

**Comment by ZhaoWeicheng98** [comment]
感谢反馈，已在最新release中修改。
