### ISSUE TITLE
请问一下自动投稿器的登录功能，一个账号投稿多个直播间

### ISSUE THREAD

**Issue by mianmian7** [AsaChiri/DDRecorder#89]
需要录制多个直播间投稿到同一个b站账号上
是每个设置里都点一次获取鉴权信息吗？
还是说手动在config文件里复制access_token、refresh_token、cookies信息，多个配置使用同一套登录信息？

**Comment by ZhaoWeicheng98** [comment]
都可以，本质上是一样的
